// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Script.sol";
import "forge-std/console2.sol";

import "../contracts/EURootAuthority.sol";
import "../contracts/AccreditationRegistry.sol";
import "../contracts/CredentialRegistry.sol";
import "../contracts/ZkpVerifierRegistry.sol";

contract Deploy is Script {

    // keccak256 of the canonical verification_key.json bytes for each circuit.
    // Generated by: ethers.utils.keccak256(fs.readFileSync('keys/<circuit>_verification_key.json'))
    bytes32 private constant AGE_VERIFICATION_VKEY_HASH =
        0x1bb318841baef22813e53b35bb707597b7c67b678d25982428a4160cc87c8edd;

    bytes32 private constant GRADUATION_YEAR_RANGE_VKEY_HASH =
        0x020538b5ad4b95ad5eef9d0b193500cf489595b116409e6590621d629df12779;

    bytes32 private constant COUNTRY_MEMBERSHIP_VKEY_HASH =
        0x05cfef55f41360da216d5c19a0e7562429db1ea509dd4922046f804c1733ebd8;

    function run() external {
        vm.startBroadcast();

        bytes32 genesisBlockHash = keccak256(bytes("EU_DID_WALLET_GENESIS"));
        string memory officialDID = "did:web:europa.eu";

        EURootAuthority rootAuthority = new EURootAuthority(
            genesisBlockHash,
            officialDID
        );

        AccreditationRegistry accreditationRegistry =
            new AccreditationRegistry(address(rootAuthority));

        CredentialRegistry credentialRegistry =
            new CredentialRegistry(address(accreditationRegistry));

        ZkpVerifierRegistry zkpVerifierRegistry =
            new ZkpVerifierRegistry();

        zkpVerifierRegistry.register(
            "ageVerification",
            AGE_VERIFICATION_VKEY_HASH,
            1
        );

        zkpVerifierRegistry.register(
            "graduationYearRange",
            GRADUATION_YEAR_RANGE_VKEY_HASH,
            1
        );

        zkpVerifierRegistry.register(
            "countryMembership",
            COUNTRY_MEMBERSHIP_VKEY_HASH,
            1
        );

        vm.stopBroadcast();

        console2.log("EURootAuthority:", address(rootAuthority));
        console2.log("AccreditationRegistry:", address(accreditationRegistry));
        console2.log("CredentialRegistry:", address(credentialRegistry));
        console2.log("ZkpVerifierRegistry:", address(zkpVerifierRegistry));
    }
}