/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AccreditationRegistry {
  export type AccreditationStruct = {
    id: BytesLike;
    issuer: AddressLike;
    subject: AddressLike;
    parentAccreditationId: BytesLike;
    scope: BigNumberish;
    permissionsHash: BytesLike;
    issuedAt: BigNumberish;
    expiresAt: BigNumberish;
    revoked: boolean;
    exists: boolean;
  };

  export type AccreditationStructOutput = [
    id: string,
    issuer: string,
    subject: string,
    parentAccreditationId: string,
    scope: bigint,
    permissionsHash: string,
    issuedAt: bigint,
    expiresAt: bigint,
    revoked: boolean,
    exists: boolean
  ] & {
    id: string;
    issuer: string;
    subject: string;
    parentAccreditationId: string;
    scope: bigint;
    permissionsHash: string;
    issuedAt: bigint;
    expiresAt: bigint;
    revoked: boolean;
    exists: boolean;
  };
}

export interface AccreditationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accreditations"
      | "accreditationsByIssuer"
      | "accreditationsBySubject"
      | "getAccreditation"
      | "getAccreditationsByIssuer"
      | "getAccreditationsBySubject"
      | "getTrustChain"
      | "hasValidAccreditation"
      | "issueAccreditation"
      | "revokeAccreditation"
      | "rootAuthority"
      | "validAccreditations"
      | "validateTrustChain"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccreditationIssued"
      | "AccreditationRevoked"
      | "AccreditationUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accreditations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "accreditationsByIssuer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "accreditationsBySubject",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccreditation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccreditationsByIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccreditationsBySubject",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustChain",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidAccreditation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "issueAccreditation",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccreditation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rootAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validAccreditations",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTrustChain",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accreditations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accreditationsByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accreditationsBySubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccreditation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccreditationsByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccreditationsBySubject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasValidAccreditation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueAccreditation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccreditation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validAccreditations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTrustChain",
    data: BytesLike
  ): Result;
}

export namespace AccreditationIssuedEvent {
  export type InputTuple = [
    id: BytesLike,
    issuer: AddressLike,
    subject: AddressLike,
    scope: BigNumberish,
    parentAccreditationId: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    issuer: string,
    subject: string,
    scope: bigint,
    parentAccreditationId: string
  ];
  export interface OutputObject {
    id: string;
    issuer: string;
    subject: string;
    scope: bigint;
    parentAccreditationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccreditationRevokedEvent {
  export type InputTuple = [
    id: BytesLike,
    revokedBy: AddressLike,
    revokedAt: BigNumberish
  ];
  export type OutputTuple = [id: string, revokedBy: string, revokedAt: bigint];
  export interface OutputObject {
    id: string;
    revokedBy: string;
    revokedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccreditationUpdatedEvent {
  export type InputTuple = [id: BytesLike, newPermissionsHash: BytesLike];
  export type OutputTuple = [id: string, newPermissionsHash: string];
  export interface OutputObject {
    id: string;
    newPermissionsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AccreditationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AccreditationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AccreditationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accreditations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        issuer: string;
        subject: string;
        parentAccreditationId: string;
        scope: bigint;
        permissionsHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  accreditationsByIssuer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  accreditationsBySubject: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getAccreditation: TypedContractMethod<
    [accreditationId: BytesLike],
    [AccreditationRegistry.AccreditationStructOutput],
    "view"
  >;

  getAccreditationsByIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  getAccreditationsBySubject: TypedContractMethod<
    [subject: AddressLike],
    [string[]],
    "view"
  >;

  getTrustChain: TypedContractMethod<
    [accreditationId: BytesLike],
    [string[]],
    "view"
  >;

  hasValidAccreditation: TypedContractMethod<
    [subject: AddressLike, scope: BigNumberish],
    [boolean],
    "view"
  >;

  issueAccreditation: TypedContractMethod<
    [
      subject: AddressLike,
      scope: BigNumberish,
      parentAccreditationId: BytesLike,
      permissionsHash: BytesLike,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  revokeAccreditation: TypedContractMethod<
    [accreditationId: BytesLike],
    [void],
    "nonpayable"
  >;

  rootAuthority: TypedContractMethod<[], [string], "view">;

  validAccreditations: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  validateTrustChain: TypedContractMethod<
    [accreditationId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accreditations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        id: string;
        issuer: string;
        subject: string;
        parentAccreditationId: string;
        scope: bigint;
        permissionsHash: string;
        issuedAt: bigint;
        expiresAt: bigint;
        revoked: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "accreditationsByIssuer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "accreditationsBySubject"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccreditation"
  ): TypedContractMethod<
    [accreditationId: BytesLike],
    [AccreditationRegistry.AccreditationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccreditationsByIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAccreditationsBySubject"
  ): TypedContractMethod<[subject: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTrustChain"
  ): TypedContractMethod<[accreditationId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "hasValidAccreditation"
  ): TypedContractMethod<
    [subject: AddressLike, scope: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueAccreditation"
  ): TypedContractMethod<
    [
      subject: AddressLike,
      scope: BigNumberish,
      parentAccreditationId: BytesLike,
      permissionsHash: BytesLike,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccreditation"
  ): TypedContractMethod<[accreditationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rootAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validAccreditations"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateTrustChain"
  ): TypedContractMethod<[accreditationId: BytesLike], [boolean], "view">;

  getEvent(
    key: "AccreditationIssued"
  ): TypedContractEvent<
    AccreditationIssuedEvent.InputTuple,
    AccreditationIssuedEvent.OutputTuple,
    AccreditationIssuedEvent.OutputObject
  >;
  getEvent(
    key: "AccreditationRevoked"
  ): TypedContractEvent<
    AccreditationRevokedEvent.InputTuple,
    AccreditationRevokedEvent.OutputTuple,
    AccreditationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AccreditationUpdated"
  ): TypedContractEvent<
    AccreditationUpdatedEvent.InputTuple,
    AccreditationUpdatedEvent.OutputTuple,
    AccreditationUpdatedEvent.OutputObject
  >;

  filters: {
    "AccreditationIssued(bytes32,address,address,uint8,bytes32)": TypedContractEvent<
      AccreditationIssuedEvent.InputTuple,
      AccreditationIssuedEvent.OutputTuple,
      AccreditationIssuedEvent.OutputObject
    >;
    AccreditationIssued: TypedContractEvent<
      AccreditationIssuedEvent.InputTuple,
      AccreditationIssuedEvent.OutputTuple,
      AccreditationIssuedEvent.OutputObject
    >;

    "AccreditationRevoked(bytes32,address,uint256)": TypedContractEvent<
      AccreditationRevokedEvent.InputTuple,
      AccreditationRevokedEvent.OutputTuple,
      AccreditationRevokedEvent.OutputObject
    >;
    AccreditationRevoked: TypedContractEvent<
      AccreditationRevokedEvent.InputTuple,
      AccreditationRevokedEvent.OutputTuple,
      AccreditationRevokedEvent.OutputObject
    >;

    "AccreditationUpdated(bytes32,bytes32)": TypedContractEvent<
      AccreditationUpdatedEvent.InputTuple,
      AccreditationUpdatedEvent.OutputTuple,
      AccreditationUpdatedEvent.OutputObject
    >;
    AccreditationUpdated: TypedContractEvent<
      AccreditationUpdatedEvent.InputTuple,
      AccreditationUpdatedEvent.OutputTuple,
      AccreditationUpdatedEvent.OutputObject
    >;
  };
}
