/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CredentialRegistry {
  export type CredentialStruct = {
    id: BytesLike;
    issuer: AddressLike;
    holder: AddressLike;
    credentialHash: BytesLike;
    credentialType: string;
    status: BigNumberish;
    issuedAt: BigNumberish;
    expiresAt: BigNumberish;
    issuerAccreditationId: BytesLike;
    exists: boolean;
  };

  export type CredentialStructOutput = [
    id: string,
    issuer: string,
    holder: string,
    credentialHash: string,
    credentialType: string,
    status: bigint,
    issuedAt: bigint,
    expiresAt: bigint,
    issuerAccreditationId: string,
    exists: boolean
  ] & {
    id: string;
    issuer: string;
    holder: string;
    credentialHash: string;
    credentialType: string;
    status: bigint;
    issuedAt: bigint;
    expiresAt: bigint;
    issuerAccreditationId: string;
    exists: boolean;
  };
}

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "REQUIRED_ISSUER_SCOPE"
      | "accreditationRegistry"
      | "batchVerifyCredentials"
      | "credentials"
      | "credentialsByHolder"
      | "credentialsByIssuer"
      | "getCredential"
      | "getCredentialStatus"
      | "getCredentialsByHolder"
      | "getCredentialsByIssuer"
      | "isActive"
      | "reactivateCredential"
      | "recordCredential"
      | "revokeCredential"
      | "suspendCredential"
      | "verifyCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialIssued"
      | "CredentialReactivated"
      | "CredentialRevoked"
      | "CredentialStatusUpdated"
      | "CredentialSuspended"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "REQUIRED_ISSUER_SCOPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accreditationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyCredentials",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "credentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialsByHolder",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "credentialsByIssuer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialsByHolder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialsByIssuer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "reactivateCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCredential",
    values: [AddressLike, BytesLike, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "suspendCredential",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCredential",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "REQUIRED_ISSUER_SCOPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accreditationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialsByHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "credentialsByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialsByHolder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialsByIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivateCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "suspendCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    id: BytesLike,
    issuer: AddressLike,
    holder: AddressLike,
    credentialType: string,
    issuerAccreditationId: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    issuer: string,
    holder: string,
    credentialType: string,
    issuerAccreditationId: string
  ];
  export interface OutputObject {
    id: string;
    issuer: string;
    holder: string;
    credentialType: string;
    issuerAccreditationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialReactivatedEvent {
  export type InputTuple = [
    id: BytesLike,
    reactivatedBy: AddressLike,
    reactivatedAt: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    reactivatedBy: string,
    reactivatedAt: bigint
  ];
  export interface OutputObject {
    id: string;
    reactivatedBy: string;
    reactivatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    id: BytesLike,
    revokedBy: AddressLike,
    revokedAt: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    id: string,
    revokedBy: string,
    revokedAt: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: string;
    revokedBy: string;
    revokedAt: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialStatusUpdatedEvent {
  export type InputTuple = [
    id: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [id: string, oldStatus: bigint, newStatus: bigint];
  export interface OutputObject {
    id: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialSuspendedEvent {
  export type InputTuple = [
    id: BytesLike,
    suspendedBy: AddressLike,
    suspendedAt: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    id: string,
    suspendedBy: string,
    suspendedAt: bigint,
    reason: string
  ];
  export interface OutputObject {
    id: string;
    suspendedBy: string;
    suspendedAt: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  REQUIRED_ISSUER_SCOPE: TypedContractMethod<[], [bigint], "view">;

  accreditationRegistry: TypedContractMethod<[], [string], "view">;

  batchVerifyCredentials: TypedContractMethod<
    [credentialIds: BytesLike[]],
    [boolean[]],
    "view"
  >;

  credentials: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        id: string;
        issuer: string;
        holder: string;
        credentialHash: string;
        credentialType: string;
        status: bigint;
        issuedAt: bigint;
        expiresAt: bigint;
        issuerAccreditationId: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  credentialsByHolder: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  credentialsByIssuer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [CredentialRegistry.CredentialStructOutput],
    "view"
  >;

  getCredentialStatus: TypedContractMethod<
    [credentialId: BytesLike],
    [bigint],
    "view"
  >;

  getCredentialsByHolder: TypedContractMethod<
    [holder: AddressLike],
    [string[]],
    "view"
  >;

  getCredentialsByIssuer: TypedContractMethod<
    [issuer: AddressLike],
    [string[]],
    "view"
  >;

  isActive: TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;

  reactivateCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [void],
    "nonpayable"
  >;

  recordCredential: TypedContractMethod<
    [
      holder: AddressLike,
      credentialHash: BytesLike,
      credentialType: string,
      issuerAccreditationId: BytesLike,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  suspendCredential: TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  verifyCredential: TypedContractMethod<
    [credentialId: BytesLike],
    [
      [boolean, bigint, boolean] & {
        isValid: boolean;
        status: bigint;
        trustChainValid: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "REQUIRED_ISSUER_SCOPE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accreditationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchVerifyCredentials"
  ): TypedContractMethod<[credentialIds: BytesLike[]], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "credentials"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        boolean
      ] & {
        id: string;
        issuer: string;
        holder: string;
        credentialHash: string;
        credentialType: string;
        status: bigint;
        issuedAt: bigint;
        expiresAt: bigint;
        issuerAccreditationId: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "credentialsByHolder"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "credentialsByIssuer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike],
    [CredentialRegistry.CredentialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCredentialStatus"
  ): TypedContractMethod<[credentialId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCredentialsByHolder"
  ): TypedContractMethod<[holder: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCredentialsByIssuer"
  ): TypedContractMethod<[issuer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "reactivateCredential"
  ): TypedContractMethod<[credentialId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordCredential"
  ): TypedContractMethod<
    [
      holder: AddressLike,
      credentialHash: BytesLike,
      credentialType: string,
      issuerAccreditationId: BytesLike,
      expiresAt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "suspendCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike],
    [
      [boolean, bigint, boolean] & {
        isValid: boolean;
        status: bigint;
        trustChainValid: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialReactivated"
  ): TypedContractEvent<
    CredentialReactivatedEvent.InputTuple,
    CredentialReactivatedEvent.OutputTuple,
    CredentialReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialStatusUpdated"
  ): TypedContractEvent<
    CredentialStatusUpdatedEvent.InputTuple,
    CredentialStatusUpdatedEvent.OutputTuple,
    CredentialStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialSuspended"
  ): TypedContractEvent<
    CredentialSuspendedEvent.InputTuple,
    CredentialSuspendedEvent.OutputTuple,
    CredentialSuspendedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(bytes32,address,address,string,bytes32)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialReactivated(bytes32,address,uint256)": TypedContractEvent<
      CredentialReactivatedEvent.InputTuple,
      CredentialReactivatedEvent.OutputTuple,
      CredentialReactivatedEvent.OutputObject
    >;
    CredentialReactivated: TypedContractEvent<
      CredentialReactivatedEvent.InputTuple,
      CredentialReactivatedEvent.OutputTuple,
      CredentialReactivatedEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address,uint256,string)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "CredentialStatusUpdated(bytes32,uint8,uint8)": TypedContractEvent<
      CredentialStatusUpdatedEvent.InputTuple,
      CredentialStatusUpdatedEvent.OutputTuple,
      CredentialStatusUpdatedEvent.OutputObject
    >;
    CredentialStatusUpdated: TypedContractEvent<
      CredentialStatusUpdatedEvent.InputTuple,
      CredentialStatusUpdatedEvent.OutputTuple,
      CredentialStatusUpdatedEvent.OutputObject
    >;

    "CredentialSuspended(bytes32,address,uint256,string)": TypedContractEvent<
      CredentialSuspendedEvent.InputTuple,
      CredentialSuspendedEvent.OutputTuple,
      CredentialSuspendedEvent.OutputObject
    >;
    CredentialSuspended: TypedContractEvent<
      CredentialSuspendedEvent.InputTuple,
      CredentialSuspendedEvent.OutputTuple,
      CredentialSuspendedEvent.OutputObject
    >;
  };
}
