/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EURootAuthority {
  export type MemberStateInfoStruct = {
    countryCode: string;
    didDocument: string;
    addedAt: BigNumberish;
    active: boolean;
  };

  export type MemberStateInfoStructOutput = [
    countryCode: string,
    didDocument: string,
    addedAt: bigint,
    active: boolean
  ] & {
    countryCode: string;
    didDocument: string;
    addedAt: bigint;
    active: boolean;
  };
}

export interface EURootAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEPLOYMENT_BLOCK"
      | "GENESIS_BLOCK_HASH"
      | "OFFICIAL_DID_DOCUMENT"
      | "addMemberState"
      | "getActiveMemberStateCount"
      | "getAllMemberStates"
      | "getMemberStateInfo"
      | "isMemberState"
      | "memberStateInfo"
      | "memberStateList"
      | "memberStates"
      | "owner"
      | "removeMemberState"
      | "updateMemberState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberStateAdded"
      | "MemberStateRemoved"
      | "MemberStateUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEPLOYMENT_BLOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GENESIS_BLOCK_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OFFICIAL_DID_DOCUMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMemberState",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMemberStateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMemberStates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberStateInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMemberState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStateInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStateList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeMemberState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMemberState",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPLOYMENT_BLOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GENESIS_BLOCK_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OFFICIAL_DID_DOCUMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMemberStateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMemberStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberStateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStateList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMemberState",
    data: BytesLike
  ): Result;
}

export namespace MemberStateAddedEvent {
  export type InputTuple = [
    stateAddress: AddressLike,
    countryCode: string,
    didDocument: string
  ];
  export type OutputTuple = [
    stateAddress: string,
    countryCode: string,
    didDocument: string
  ];
  export interface OutputObject {
    stateAddress: string;
    countryCode: string;
    didDocument: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateRemovedEvent {
  export type InputTuple = [stateAddress: AddressLike, countryCode: string];
  export type OutputTuple = [stateAddress: string, countryCode: string];
  export interface OutputObject {
    stateAddress: string;
    countryCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateUpdatedEvent {
  export type InputTuple = [stateAddress: AddressLike, didDocument: string];
  export type OutputTuple = [stateAddress: string, didDocument: string];
  export interface OutputObject {
    stateAddress: string;
    didDocument: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EURootAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): EURootAuthority;
  waitForDeployment(): Promise<this>;

  interface: EURootAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEPLOYMENT_BLOCK: TypedContractMethod<[], [bigint], "view">;

  GENESIS_BLOCK_HASH: TypedContractMethod<[], [string], "view">;

  OFFICIAL_DID_DOCUMENT: TypedContractMethod<[], [string], "view">;

  addMemberState: TypedContractMethod<
    [stateAddress: AddressLike, countryCode: string, didDocument: string],
    [void],
    "nonpayable"
  >;

  getActiveMemberStateCount: TypedContractMethod<[], [bigint], "view">;

  getAllMemberStates: TypedContractMethod<[], [string[]], "view">;

  getMemberStateInfo: TypedContractMethod<
    [state: AddressLike],
    [EURootAuthority.MemberStateInfoStructOutput],
    "view"
  >;

  isMemberState: TypedContractMethod<[state: AddressLike], [boolean], "view">;

  memberStateInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        countryCode: string;
        didDocument: string;
        addedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  memberStateList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  memberStates: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeMemberState: TypedContractMethod<
    [stateAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  updateMemberState: TypedContractMethod<
    [stateAddress: AddressLike, didDocument: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEPLOYMENT_BLOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GENESIS_BLOCK_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OFFICIAL_DID_DOCUMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addMemberState"
  ): TypedContractMethod<
    [stateAddress: AddressLike, countryCode: string, didDocument: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveMemberStateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllMemberStates"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMemberStateInfo"
  ): TypedContractMethod<
    [state: AddressLike],
    [EURootAuthority.MemberStateInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMemberState"
  ): TypedContractMethod<[state: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "memberStateInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        countryCode: string;
        didDocument: string;
        addedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "memberStateList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "memberStates"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMemberState"
  ): TypedContractMethod<[stateAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMemberState"
  ): TypedContractMethod<
    [stateAddress: AddressLike, didDocument: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MemberStateAdded"
  ): TypedContractEvent<
    MemberStateAddedEvent.InputTuple,
    MemberStateAddedEvent.OutputTuple,
    MemberStateAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateRemoved"
  ): TypedContractEvent<
    MemberStateRemovedEvent.InputTuple,
    MemberStateRemovedEvent.OutputTuple,
    MemberStateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateUpdated"
  ): TypedContractEvent<
    MemberStateUpdatedEvent.InputTuple,
    MemberStateUpdatedEvent.OutputTuple,
    MemberStateUpdatedEvent.OutputObject
  >;

  filters: {
    "MemberStateAdded(address,string,string)": TypedContractEvent<
      MemberStateAddedEvent.InputTuple,
      MemberStateAddedEvent.OutputTuple,
      MemberStateAddedEvent.OutputObject
    >;
    MemberStateAdded: TypedContractEvent<
      MemberStateAddedEvent.InputTuple,
      MemberStateAddedEvent.OutputTuple,
      MemberStateAddedEvent.OutputObject
    >;

    "MemberStateRemoved(address,string)": TypedContractEvent<
      MemberStateRemovedEvent.InputTuple,
      MemberStateRemovedEvent.OutputTuple,
      MemberStateRemovedEvent.OutputObject
    >;
    MemberStateRemoved: TypedContractEvent<
      MemberStateRemovedEvent.InputTuple,
      MemberStateRemovedEvent.OutputTuple,
      MemberStateRemovedEvent.OutputObject
    >;

    "MemberStateUpdated(address,string)": TypedContractEvent<
      MemberStateUpdatedEvent.InputTuple,
      MemberStateUpdatedEvent.OutputTuple,
      MemberStateUpdatedEvent.OutputObject
    >;
    MemberStateUpdated: TypedContractEvent<
      MemberStateUpdatedEvent.InputTuple,
      MemberStateUpdatedEvent.OutputTuple,
      MemberStateUpdatedEvent.OutputObject
    >;
  };
}
