/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EURootAuthority {
  export type MemberStateInfoStruct = {
    countryCode: string;
    didDocument: string;
    addedAt: BigNumberish;
    active: boolean;
  };

  export type MemberStateInfoStructOutput = [
    countryCode: string,
    didDocument: string,
    addedAt: bigint,
    active: boolean
  ] & {
    countryCode: string;
    didDocument: string;
    addedAt: bigint;
    active: boolean;
  };
}

export interface EURootAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "APPROVAL_THRESHOLD"
      | "DEPLOYMENT_BLOCK"
      | "GENESIS_BLOCK_HASH"
      | "MIN_WITNESS_SIGNATURES"
      | "OFFICIAL_DID_DOCUMENT"
      | "TOTAL_MEMBER_STATES"
      | "addDeploymentWitness"
      | "bootstrapMemberStates"
      | "deploymentCeremonyCompleted"
      | "deploymentWitnesses"
      | "executeProposal"
      | "getActiveMemberStateCount"
      | "getAllMemberStates"
      | "getMemberStateInfo"
      | "isMemberState"
      | "memberStateInfo"
      | "memberStateList"
      | "memberStates"
      | "proposalVotes"
      | "proposals"
      | "proposeAddMemberState"
      | "verifyDeploymentCeremony"
      | "voteOnProposal"
      | "witnessCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeploymentCeremonyCompleted"
      | "DeploymentWitnessAdded"
      | "MemberStateAdded"
      | "MemberStateRemoved"
      | "MemberStateUpdated"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalVoted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "APPROVAL_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPLOYMENT_BLOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GENESIS_BLOCK_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WITNESS_SIGNATURES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OFFICIAL_DID_DOCUMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOTAL_MEMBER_STATES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDeploymentWitness",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bootstrapMemberStates",
    values: [AddressLike[], string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentCeremonyCompleted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentWitnesses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveMemberStateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMemberStates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberStateInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMemberState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStateInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStateList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "memberStates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVotes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeAddMemberState",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDeploymentCeremony",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnProposal",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "witnessCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APPROVAL_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPLOYMENT_BLOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GENESIS_BLOCK_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WITNESS_SIGNATURES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OFFICIAL_DID_DOCUMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOTAL_MEMBER_STATES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDeploymentWitness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bootstrapMemberStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentCeremonyCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentWitnesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveMemberStateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMemberStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberStateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStateInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStateList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberStates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeAddMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDeploymentCeremony",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "witnessCount",
    data: BytesLike
  ): Result;
}

export namespace DeploymentCeremonyCompletedEvent {
  export type InputTuple = [
    blockNumber: BigNumberish,
    witnessCount: BigNumberish
  ];
  export type OutputTuple = [blockNumber: bigint, witnessCount: bigint];
  export interface OutputObject {
    blockNumber: bigint;
    witnessCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeploymentWitnessAddedEvent {
  export type InputTuple = [witness: AddressLike, totalWitnesses: BigNumberish];
  export type OutputTuple = [witness: string, totalWitnesses: bigint];
  export interface OutputObject {
    witness: string;
    totalWitnesses: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateAddedEvent {
  export type InputTuple = [
    stateAddress: AddressLike,
    countryCode: string,
    didDocument: string
  ];
  export type OutputTuple = [
    stateAddress: string,
    countryCode: string,
    didDocument: string
  ];
  export interface OutputObject {
    stateAddress: string;
    countryCode: string;
    didDocument: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateRemovedEvent {
  export type InputTuple = [stateAddress: AddressLike, countryCode: string];
  export type OutputTuple = [stateAddress: string, countryCode: string];
  export interface OutputObject {
    stateAddress: string;
    countryCode: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateUpdatedEvent {
  export type InputTuple = [stateAddress: AddressLike, didDocument: string];
  export type OutputTuple = [stateAddress: string, didDocument: string];
  export interface OutputObject {
    stateAddress: string;
    didDocument: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    proposalType: BigNumberish,
    target: AddressLike
  ];
  export type OutputTuple = [
    proposalId: string,
    proposalType: bigint,
    target: string
  ];
  export interface OutputObject {
    proposalId: string;
    proposalType: bigint;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BytesLike, executedAt: BigNumberish];
  export type OutputTuple = [proposalId: string, executedAt: bigint];
  export interface OutputObject {
    proposalId: string;
    executedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalVotedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    voter: AddressLike,
    support: boolean
  ];
  export type OutputTuple = [
    proposalId: string,
    voter: string,
    support: boolean
  ];
  export interface OutputObject {
    proposalId: string;
    voter: string;
    support: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EURootAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): EURootAuthority;
  waitForDeployment(): Promise<this>;

  interface: EURootAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  APPROVAL_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  DEPLOYMENT_BLOCK: TypedContractMethod<[], [bigint], "view">;

  GENESIS_BLOCK_HASH: TypedContractMethod<[], [string], "view">;

  MIN_WITNESS_SIGNATURES: TypedContractMethod<[], [bigint], "view">;

  OFFICIAL_DID_DOCUMENT: TypedContractMethod<[], [string], "view">;

  TOTAL_MEMBER_STATES: TypedContractMethod<[], [bigint], "view">;

  addDeploymentWitness: TypedContractMethod<
    [witness: AddressLike],
    [void],
    "nonpayable"
  >;

  bootstrapMemberStates: TypedContractMethod<
    [
      initialStates: AddressLike[],
      countryCodes: string[],
      didDocuments: string[]
    ],
    [void],
    "nonpayable"
  >;

  deploymentCeremonyCompleted: TypedContractMethod<[], [boolean], "view">;

  deploymentWitnesses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  executeProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  getActiveMemberStateCount: TypedContractMethod<[], [bigint], "view">;

  getAllMemberStates: TypedContractMethod<[], [string[]], "view">;

  getMemberStateInfo: TypedContractMethod<
    [state: AddressLike],
    [EURootAuthority.MemberStateInfoStructOutput],
    "view"
  >;

  isMemberState: TypedContractMethod<[state: AddressLike], [boolean], "view">;

  memberStateInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        countryCode: string;
        didDocument: string;
        addedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  memberStateList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  memberStates: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  proposalVotes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        proposalType: bigint;
        target: string;
        data: string;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        executedAt: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  proposeAddMemberState: TypedContractMethod<
    [stateAddress: AddressLike, countryCode: string, didDocument: string],
    [string],
    "nonpayable"
  >;

  verifyDeploymentCeremony: TypedContractMethod<[], [boolean], "view">;

  voteOnProposal: TypedContractMethod<
    [proposalId: BytesLike, support: boolean],
    [void],
    "nonpayable"
  >;

  witnessCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "APPROVAL_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPLOYMENT_BLOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GENESIS_BLOCK_HASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_WITNESS_SIGNATURES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OFFICIAL_DID_DOCUMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TOTAL_MEMBER_STATES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addDeploymentWitness"
  ): TypedContractMethod<[witness: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bootstrapMemberStates"
  ): TypedContractMethod<
    [
      initialStates: AddressLike[],
      countryCodes: string[],
      didDocuments: string[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deploymentCeremonyCompleted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "deploymentWitnesses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveMemberStateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllMemberStates"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMemberStateInfo"
  ): TypedContractMethod<
    [state: AddressLike],
    [EURootAuthority.MemberStateInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMemberState"
  ): TypedContractMethod<[state: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "memberStateInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        countryCode: string;
        didDocument: string;
        addedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "memberStateList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "memberStates"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposalVotes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, boolean] & {
        proposalType: bigint;
        target: string;
        data: string;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        executedAt: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeAddMemberState"
  ): TypedContractMethod<
    [stateAddress: AddressLike, countryCode: string, didDocument: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDeploymentCeremony"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "voteOnProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike, support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "witnessCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DeploymentCeremonyCompleted"
  ): TypedContractEvent<
    DeploymentCeremonyCompletedEvent.InputTuple,
    DeploymentCeremonyCompletedEvent.OutputTuple,
    DeploymentCeremonyCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DeploymentWitnessAdded"
  ): TypedContractEvent<
    DeploymentWitnessAddedEvent.InputTuple,
    DeploymentWitnessAddedEvent.OutputTuple,
    DeploymentWitnessAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateAdded"
  ): TypedContractEvent<
    MemberStateAddedEvent.InputTuple,
    MemberStateAddedEvent.OutputTuple,
    MemberStateAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateRemoved"
  ): TypedContractEvent<
    MemberStateRemovedEvent.InputTuple,
    MemberStateRemovedEvent.OutputTuple,
    MemberStateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateUpdated"
  ): TypedContractEvent<
    MemberStateUpdatedEvent.InputTuple,
    MemberStateUpdatedEvent.OutputTuple,
    MemberStateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalVoted"
  ): TypedContractEvent<
    ProposalVotedEvent.InputTuple,
    ProposalVotedEvent.OutputTuple,
    ProposalVotedEvent.OutputObject
  >;

  filters: {
    "DeploymentCeremonyCompleted(uint256,uint256)": TypedContractEvent<
      DeploymentCeremonyCompletedEvent.InputTuple,
      DeploymentCeremonyCompletedEvent.OutputTuple,
      DeploymentCeremonyCompletedEvent.OutputObject
    >;
    DeploymentCeremonyCompleted: TypedContractEvent<
      DeploymentCeremonyCompletedEvent.InputTuple,
      DeploymentCeremonyCompletedEvent.OutputTuple,
      DeploymentCeremonyCompletedEvent.OutputObject
    >;

    "DeploymentWitnessAdded(address,uint256)": TypedContractEvent<
      DeploymentWitnessAddedEvent.InputTuple,
      DeploymentWitnessAddedEvent.OutputTuple,
      DeploymentWitnessAddedEvent.OutputObject
    >;
    DeploymentWitnessAdded: TypedContractEvent<
      DeploymentWitnessAddedEvent.InputTuple,
      DeploymentWitnessAddedEvent.OutputTuple,
      DeploymentWitnessAddedEvent.OutputObject
    >;

    "MemberStateAdded(address,string,string)": TypedContractEvent<
      MemberStateAddedEvent.InputTuple,
      MemberStateAddedEvent.OutputTuple,
      MemberStateAddedEvent.OutputObject
    >;
    MemberStateAdded: TypedContractEvent<
      MemberStateAddedEvent.InputTuple,
      MemberStateAddedEvent.OutputTuple,
      MemberStateAddedEvent.OutputObject
    >;

    "MemberStateRemoved(address,string)": TypedContractEvent<
      MemberStateRemovedEvent.InputTuple,
      MemberStateRemovedEvent.OutputTuple,
      MemberStateRemovedEvent.OutputObject
    >;
    MemberStateRemoved: TypedContractEvent<
      MemberStateRemovedEvent.InputTuple,
      MemberStateRemovedEvent.OutputTuple,
      MemberStateRemovedEvent.OutputObject
    >;

    "MemberStateUpdated(address,string)": TypedContractEvent<
      MemberStateUpdatedEvent.InputTuple,
      MemberStateUpdatedEvent.OutputTuple,
      MemberStateUpdatedEvent.OutputObject
    >;
    MemberStateUpdated: TypedContractEvent<
      MemberStateUpdatedEvent.InputTuple,
      MemberStateUpdatedEvent.OutputTuple,
      MemberStateUpdatedEvent.OutputObject
    >;

    "ProposalCreated(bytes32,uint8,address)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(bytes32,uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalVoted(bytes32,address,bool)": TypedContractEvent<
      ProposalVotedEvent.InputTuple,
      ProposalVotedEvent.OutputTuple,
      ProposalVotedEvent.OutputObject
    >;
    ProposalVoted: TypedContractEvent<
      ProposalVotedEvent.InputTuple,
      ProposalVotedEvent.OutputTuple,
      ProposalVotedEvent.OutputObject
    >;
  };
}
