import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';

// Poseidon Merkle root of depth-5 tree over 27 EU ISO-3166-1 numeric codes, padded to 32 leaves.
// Generated by zkp-service/scripts/generate-eu-merkle.mjs using circomlibjs Poseidon.
export const EU_MERKLE_ROOT = '8428341660130688306333484504011921408645278038482389394981986252670980317908';

type CircuitName = 'ageVerification' | 'graduationYearRange' | 'countryMembership';

const CIRCUIT_ASSETS: Record<CircuitName, { wasm: any; zkey: any; vkey: any }> = {
  ageVerification: {
    wasm: require('../../assets/circuits/ageVerification/circuit.wasm'),
    zkey: require('../../assets/circuits/ageVerification/final.zkey'),
    vkey: require('../../assets/circuits/ageVerification/verification_key.json'),
  },
  graduationYearRange: {
    wasm: require('../../assets/circuits/graduationYearRange/circuit.wasm'),
    zkey: require('../../assets/circuits/graduationYearRange/final.zkey'),
    vkey: require('../../assets/circuits/graduationYearRange/verification_key.json'),
  },
  countryMembership: {
    wasm: require('../../assets/circuits/countryMembership/circuit.wasm'),
    zkey: require('../../assets/circuits/countryMembership/final.zkey'),
    vkey: require('../../assets/circuits/countryMembership/verification_key.json'),
  },
};

async function readBinaryAsset(module: any): Promise<Uint8Array> {
  const asset = Asset.fromModule(module);
  await asset.downloadAsync();
  const base64 = await FileSystem.readAsStringAsync(asset.localUri!, {
    encoding: FileSystem.EncodingType.Base64,
  });
  const binaryStr = atob(base64);
  const buffer = new Uint8Array(binaryStr.length);
  for (let i = 0; i < binaryStr.length; i++) buffer[i] = binaryStr.charCodeAt(i);
  return buffer;
}

class ZkpService {
  /**
   * Generates a Groth16 ZKP proof entirely on-device.
   * Private inputs (age, country code, graduation year) never leave the device.
   */
  async prove(
    circuitName: CircuitName,
    input: Record<string, any>,
  ): Promise<{ proof: any; publicSignals: string[] }> {
    // Lazy import to avoid Metro bundler Node.js resolution issues at startup
    const snarkjs = await import('snarkjs');
    const { wasm, zkey } = CIRCUIT_ASSETS[circuitName];
    const wasmBuffer = await readBinaryAsset(wasm);
    const zkeyBuffer = await readBinaryAsset(zkey);
    const { proof, publicSignals } = await (snarkjs as any).groth16.fullProve(
      input,
      { type: 'mem', data: wasmBuffer },
      { type: 'mem', data: zkeyBuffer },
    );
    return { proof, publicSignals };
  }

  async verify(
    circuitName: CircuitName,
    proof: any,
    publicSignals: string[],
  ): Promise<boolean> {
    const snarkjs = await import('snarkjs');
    const { vkey } = CIRCUIT_ASSETS[circuitName];
    const vKeyJson = (vkey as any).default ?? vkey;
    return (snarkjs as any).groth16.verify(vKeyJson, publicSignals, proof);
  }
}

export default new ZkpService();
