import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';
import zkpBridge from './zkpBridge';

// Poseidon Merkle root of depth-5 tree over 27 EU ISO-3166-1 numeric codes, padded to 32 leaves.
// Generated by zkp-service/scripts/generate-eu-merkle.mjs using circomlibjs Poseidon.
export const EU_MERKLE_ROOT = '8428341660130688306333484504011921408645278038482389394981986252670980317908';

const merkleData = require('../../assets/eu-country-merkle.json') as {
  paths: Record<string, { numeric: number; leafIndex: number; pathElements: string[]; pathIndices: number[] }>;
};

export interface MerklePath {
  numeric: number;
  pathElements: string[];
  pathIndices: number[];
}

export function getMerklePathForCountry(iso2Code: string): MerklePath {
  const entry = merkleData.paths[iso2Code.toUpperCase()];
  if (!entry) {
    throw new Error(`Country "${iso2Code}" is not in the EU Merkle tree. Only EU member states can generate this proof.`);
  }
  return { numeric: entry.numeric, pathElements: entry.pathElements, pathIndices: entry.pathIndices };
}

type CircuitName = 'ageVerification' | 'graduationYearRange' | 'countryMembership';

const CIRCUIT_ASSETS: Record<CircuitName, { wasm: any; zkey: any; vkey: any }> = {
  ageVerification: {
    wasm: require('../../assets/circuits/ageVerification/circuit.wasm'),
    zkey: require('../../assets/circuits/ageVerification/final.zkey'),
    vkey: require('../../assets/circuits/ageVerification/verification_key.json'),
  },
  graduationYearRange: {
    wasm: require('../../assets/circuits/graduationYearRange/circuit.wasm'),
    zkey: require('../../assets/circuits/graduationYearRange/final.zkey'),
    vkey: require('../../assets/circuits/graduationYearRange/verification_key.json'),
  },
  countryMembership: {
    wasm: require('../../assets/circuits/countryMembership/circuit.wasm'),
    zkey: require('../../assets/circuits/countryMembership/final.zkey'),
    vkey: require('../../assets/circuits/countryMembership/verification_key.json'),
  },
};

async function readAssetAsBase64(module: any): Promise<string> {
  const asset = Asset.fromModule(module);
  await asset.downloadAsync();
  return FileSystem.readAsStringAsync(asset.localUri!, {
    encoding: FileSystem.EncodingType.Base64,
  });
}

class ZkpService {
  async prove(
    circuitName: CircuitName,
    input: Record<string, any>,
  ): Promise<{ proof: any; publicSignals: string[] }> {
    const { wasm, zkey } = CIRCUIT_ASSETS[circuitName];
    const [wasmB64, zkeyB64] = await Promise.all([
      readAssetAsBase64(wasm),
      readAssetAsBase64(zkey),
    ]);
    return zkpBridge.prove(input, wasmB64, zkeyB64);
  }

  async verify(
    circuitName: CircuitName,
    proof: any,
    publicSignals: string[],
  ): Promise<boolean> {
    const { vkey } = CIRCUIT_ASSETS[circuitName];
    const vKeyJson = (vkey as any).default ?? vkey;
    const proofValid = await zkpBridge.verify(proof, publicSignals, vKeyJson);
    // All three circuits declare 'valid' as their first public output signal.
    // groth16.verify only checks cryptographic consistency — it does not check
    // whether the circuit's output is 1. We must verify publicSignals[0] === '1'
    // explicitly, otherwise a proof generated with a failing input (valid=0) would
    // pass verification. The countryMembership circuit additionally enforces
    // valid === 1 as a hard circuit constraint, but age and graduation do not.
    return proofValid && publicSignals[0] === '1';
  }
}

export default new ZkpService();
