import * as FileSystem from 'expo-file-system';
import { Asset } from 'expo-asset';
import zkpBridge from './zkpBridge';

// Poseidon Merkle root of depth-5 tree over 27 EU ISO-3166-1 numeric codes, padded to 32 leaves.
// Generated by zkp-service/scripts/generate-eu-merkle.mjs using circomlibjs Poseidon.
export const EU_MERKLE_ROOT = '8428341660130688306333484504011921408645278038482389394981986252670980317908';

type CircuitName = 'ageVerification' | 'graduationYearRange' | 'countryMembership';

const CIRCUIT_ASSETS: Record<CircuitName, { wasm: any; zkey: any; vkey: any }> = {
  ageVerification: {
    wasm: require('../../assets/circuits/ageVerification/circuit.wasm'),
    zkey: require('../../assets/circuits/ageVerification/final.zkey'),
    vkey: require('../../assets/circuits/ageVerification/verification_key.json'),
  },
  graduationYearRange: {
    wasm: require('../../assets/circuits/graduationYearRange/circuit.wasm'),
    zkey: require('../../assets/circuits/graduationYearRange/final.zkey'),
    vkey: require('../../assets/circuits/graduationYearRange/verification_key.json'),
  },
  countryMembership: {
    wasm: require('../../assets/circuits/countryMembership/circuit.wasm'),
    zkey: require('../../assets/circuits/countryMembership/final.zkey'),
    vkey: require('../../assets/circuits/countryMembership/verification_key.json'),
  },
};

async function readAssetAsBase64(module: any): Promise<string> {
  const asset = Asset.fromModule(module);
  await asset.downloadAsync();
  return FileSystem.readAsStringAsync(asset.localUri!, {
    encoding: FileSystem.EncodingType.Base64,
  });
}

class ZkpService {
  async prove(
    circuitName: CircuitName,
    input: Record<string, any>,
  ): Promise<{ proof: any; publicSignals: string[] }> {
    const { wasm, zkey } = CIRCUIT_ASSETS[circuitName];
    const [wasmB64, zkeyB64] = await Promise.all([
      readAssetAsBase64(wasm),
      readAssetAsBase64(zkey),
    ]);
    return zkpBridge.prove(input, wasmB64, zkeyB64);
  }

  async verify(
    circuitName: CircuitName,
    proof: any,
    publicSignals: string[],
  ): Promise<boolean> {
    const { vkey } = CIRCUIT_ASSETS[circuitName];
    const vKeyJson = (vkey as any).default ?? vkey;
    return zkpBridge.verify(proof, publicSignals, vKeyJson);
  }
}

export default new ZkpService();
